# config/config.yaml

# Target communities
subreddits:
  primary:
    - devops
    - selfhosted
    - webdev
    - SaaS
    - learnprogramming
    - startups
    - sideproject
    - experienceddevs
  exploratory_limit: 12             # Max exploratory subreddits at a time
  exploratory_refresh_days: 7       # How often to refresh improvised list
  exploratory_percentage: 10        # % of posts from exploratory communities
  primary_percentage: 90            # % of posts from configured communities

# Reddit scraping settings
scraper:
  min_post_age_days: 5              # Post must be at least 5 days old
  max_post_age_days: 30             # Ignore posts older than 3 months
  max_items_per_day: 300            # Total posts/comments scraped per run
  include_comments: true
  rate_limit_per_minute: 60         # Reddit API rate limit

# API Keys
api_keys:
  deepseek: "your-deepseek-api-key"
  clickbank: "your-clickbank-api-key" 
  shareasale: "your-shareasale-api-key"
  impactradius: "your-impact-api-key"
  openai:
    model_filter: gpt-4o-mini
    model_deep: gpt-4.1
    use_batch_api: true
    monthly_budget_usd: 100
    max_tokens_per_post: 1000
    cache_input: true

# Affiliate Networks
networks:
  clickbank:
    base_url: "https://www.clickbank.com/marketplace/ai-tools/"
  shareasale:
    base_url: "https://www.shareasale.com/ai-saas/"
  impactradius:
    base_url: "https://app.impact.com/"

# Content Generation
content:
  linkedin:
    article_length: 1500
  reddit:
    post_length: 300

# Scoring weights (used in filtering and final ranking)
scoring:
  relevance_weight: 0.4
  emotion_weight: 0.2
  pain_point_weight: 0.3
  recent_activity_weight: 0.1       # Prioritize active threads
  output_top_n: 10                  # Number of final posts to recommend

# Database settings
database:
  path: data/db.sqlite
  retention_days: 90                # Auto-remove posts older than this

# Logging & output
log_level: DEBUG                   # For debug & reuse
save_batch_payloads: true           # For debug & reuse

cleanup:
  batch_response_retention_days: 3 # Cleanup batch responses older than this